name: CI/CD
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
      - name: "Install Dependencies"
        run: yarn --frozen-lockfile

      - name: Setup Sentry CLI
        uses: mathieu-bour/setup-sentry-cli@v1.3.0
        with:
          token: ${{ SECRETS.SENTRY_TOKEN }}
          organization: haichuan-zhang
          project: photos

      - uses: nrwl/nx-set-shas@v3

      - run: npx nx workspace-lint
      - name: Build
        run: npx nx affected --target=build --parallel=3
      - name: Docker Image
        run: INPUT_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} npx nx affected --target=container --parallel=3
